import { nextJsConfig } from "@repo/eslint-config/next-js";
import globals from "globals";

/** @type {import("eslint").Linter.Config[]} */
export default [
  // Generated by `payload migrate:create` — not hand-authored, don't lint.
  {
    ignores: ["src/migrations/**"],
  },
  ...nextJsConfig,
  {
    files: ["**/*.config.cjs", "**/*.config.js"],
    languageOptions: {
      globals: globals.node,
    },
  },
];

